name: Pull Request

on:
  workflow_call:
    inputs:
      concurrency_cancel:
        default: true
        description: "The concurrency cancel to use"
        required: false
        type: boolean
      concurrency_group:
        default: "pull_request_${{ github.ref }}"
        description: "The concurrency group to use"
        required: false
        type: string
      dockerhub_user:
        default: "containifyci"
        description: "The dockerhub user to use"
        required: false
        type: string
      install_binary:
        default: true
        description: "Install the engine binary"
        required: false
        type: boolean
      runs_on:
        default: "ubuntu-24.04"
        description: "The runner vm image to use for example ubuntu-24.04"
        required: false
        type: string

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: ${{ inputs.concurrency_cancel }}

permissions:
  contents: write # for checkout
  pull-requests: write # for updating pr

jobs:
  build:
    name: Build
    uses: containifyci/engine-ci/.github/workflows/engine-ci-workflow.yml@v0
    secrets: inherit
    with:
      install_binary: ${{ inputs.install_binary }}
      dockerhub_user: ${{ inputs.dockerhub_user }}
