name: Release

on:
  workflow_call:
    inputs:
      concurrency_cancel:
        default: true
        description: "The concurrency cancel to use"
        required: false
        type: boolean
      concurrency_group:
        default: "release_${{ github.ref }}"
        description: "The concurrency group to use"
        required: false
        type: string
      dockerhub_user:
        default: "containifyci"
        description: "The dockerhub user to use"
        required: false
        type: string
      install_binary:
        default: true
        description: "Install the engine binary"
        required: false
        type: boolean
      noNewCommitBehavior:
        default: "silent"
        description: "The no new commit behavior to use"
        required: false
        type: string
      runs_on:
        default: "ubuntu-24.04"
        description: "The runner vm image to use for example ubuntu-24.04"
        required: false
        type: string
    secrets:
      RELEASE_GITHUB_TOKEN:
        description: "The github token to use for release"
        required: false

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: ${{ inputs.concurrency_cancel }}

permissions:
  contents: write # for checkout
  pull-requests: write # for updating pr

jobs:
  build:
    name: Build
    uses: containifyci/engine-ci/.github/workflows/engine-ci-workflow.yml@v0
    secrets: inherit
    with:
      dockerhub_user: ${{ inputs.dockerhub_user }}
      install_binary: ${{ inputs.install_binary }}
      runs_on: ${{ inputs.runs_on }}
  release:
    runs-on: ${{ inputs.runs_on}}
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: ${{ inputs.noNewCommitBehavior }}
          skipInvalidTags: true
          maxTagsToFetch: 50
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.semver.outputs.next
        with:
          allowUpdates: true
          # draft: true
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
